### ISSUE TITLE
List all subgraph

### ISSUE THREAD

**Issue by taijusanagi** [block-base/nft-analytics#2]
## Expected outcome
- subgraph list
- check subgraph data availability
- simple data integration diagram

please update readme too.

**Comment by taijusanagi** [comment]
I put a link to this issue in the readme, so please keep evidence in this issue.

Please add a simple data integration diagram screenshot in this TBD section too.

<img width="687" alt="Screen Shot 2022-08-30 at 15 02 03" src="https://user-images.githubusercontent.com/38043569/187361389-2221c5e4-0de2-4238-bc4d-988be252dcdb.png">

**Comment by ksuhara** [comment]
use this mainly
- [721 Marketplace](https://thegraph.com/explorer/subgraph?id=B333F7Ra4kuVBSwHFDfH9x9N1341GYHvdfpV94KY8Gmv&view=Overview)
  - cover OpenSea, LooksRare, X2Y2

might use for additional info
- [LooksRare Exchange V1](https://thegraph.com/explorer/subgraph?id=HJaSxvt1vH2nawRS53fGdxSrBbUZnYh52V4k8MjiPa7t&view=Overview)
- [X2Y2 Ethereum](https://thegraph.com/explorer/subgraph?id=8ZjJGsaKea7WwLJPJNdHXPGsvXDe3iq2231aRjgBPisi&view=Overview)
- [eip1155](https://thegraph.com/explorer/subgraph?id=GCQVLurkeZrdMf4t5v5NyeWJY8pHhfE9sinjFMjLYd9C&view=Overview)

maybe integrate in the future
- [NFTX](https://thegraph.com/explorer/subgraph?id=4gZf3atMXjYDh4g48Zr83NFX3rkvZED86VqMNhgEXgLc&view=Overview)

**Comment by taijusanagi** [comment]
close this.
