### ISSUE TITLE
System architecture

### ISSUE THREAD

**Issue by taijusanagi** [block-base/nft-analytics#4]
Let's prepare system architecture

**Comment by ksuhara** [comment]
for MVP, I'm thinking of using only 1 subgraph. so very simple architecture

<img width="840" alt="スクリーンショット 2022-09-01 10 55 32" src="https://user-images.githubusercontent.com/45842611/187815761-22d7b4c7-b50a-4dc0-bfcf-5f87c5fb72cf.png">

**Comment by taijusanagi** [comment]
Nice!

For the typing and query, I suggest using the auto-generate type and query with apollo react hook.

Seems nice, you can close this anytime.
